services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tenpochallenge
      SPRING_DATASOURCE_USERNAME: bbeltran
      SPRING_DATASOURCE_PASSWORD: bbeltran
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tenpochallenge
      POSTGRES_USER: bbeltran
      POSTGRES_PASSWORD: bbeltran
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app_network

volumes:
  postgres-data:
  redis-data:

networks:
  app_network:
    driver: bridge
